FROM node:lts-alpine

RUN npm install -g http-server  
#npm@latest

WORKDIR /frontend

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 8080

#CMD [ "npm", "run", "dev", "--host", "0.0.0.0" ]
CMD [ "http-server", "dist" ]