FROM node:18-alpine

WORKDIR /frontend

COPY package*.json ./
COPY package-lock.json ./ 

RUN npm install --legacy-peer-deps || yarn install || pnpm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "serve"]